### PR TITLE
feat: Address `set-output` deprecation

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed addresses the `set-output` deprecation of workflows: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The recommended upgrade step is to bump the core package.

cc https://github.com/jenkins-infra/helpdesk/issues/3176 for my internal reference.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by NotMyFault** [comment]
Thanks for the quick merge! Would you mind cutting a release of 2.1.0, please?

**Comment by eps1lon** [comment]
2.1 should be part of main and 2.x.  what is currently missing for you?

**Comment by NotMyFault** [comment]
Does GitHub no longer demand a tag for actions to be consumed as the major version?

**Pull request merged**
